### ISSUE TITLE
 介绍list(quicklist)一章中示意图有误

### ISSUE THREAD

**Issue by zhao520a1a** [zpoint/Redis-Internals#16]
你好，我在学习redis内部数据结构实现机制中，参考学习了您写的文章。但是发现在阅读list(quicklist)一章中，最后一张图片画的好像有些问题；于我理解的有些不符，但也不排除是我理解的有问题；望指教： 
我认为当执行了以下命令：
```
127.0.0.1:6379> linsert lst after bb2 123
(integer) 10
```
下面的示意图中： 中间两个quicklistNode的顺序和其中的ziplist中节点的顺序是有问题的。

希望待有空时核查一下，期待互相交流沟通。

**Comment by zpoint** [comment]
您好, 能说明一下具体的问题吗, 我再去验证一下

之前是照着 [inspect_list](https://github.com/zpoint/Redis-Internals/blob/5.0/inspect/inspect_list.c) 的结果画的

**Comment by zhao520a1a** [comment]
Github中list(quicklist)一章中，最后
我在配置文件做了如下两行的更改
list-max-ziplist-size 3
list-compress-depth 0

插入节点
127.0.0.1:6379> del lst
(integer) 1
127.0.0.1:6379> lpush lst aa1 aa2 aa3 bb1 bb2 bb3 cc1 cc2 cc3
(integer) 8








将节点插入到中间部分 — > 
127.0.0.1:6379> linsert lst after bb2 123
(integer) 10








注：上面是将 “123” 添加到 “bb2”之后，因此列表中所存储的元素应该是：

aa1 aa2 aa3 bb1 bb2 123 bb3 cc1 cc2 cc3




因为存储了值 bb2 的 quicklistNode 是满的了, 这个节点会被拆开 

（我认为下图存些问题）




下面是我认为内部的存储结构示意图： （绿色的箭头代表的是指针），请指教



| |
zhaojinxin_golden
|
|
zhaojinxin_golden@163.com
|
 


在2020年02月6日 11:16，zpoint<notifications@github.com> 写道：

您好, 能说明一下具体的问题吗, 我再去验证一下

之前是照着 inspect_list 的结果画的

**Comment by zhao520a1a** [comment]
Github中list(quicklist)一章中，最后一段写道：

- 我在配置文件做了如下两行的更改
```
list-max-ziplist-size 3
list-compress-depth 0
```
- 插入节点
127.0.0.1:6379> del lst
(integer) 1
127.0.0.1:6379> lpush lst aa1 aa2 aa3 bb1 bb2 bb3 cc1 cc2 cc3
(integer) 8
![image](https://user-images.githubusercontent.com/18511674/73904839-58501300-48d8-11ea-8aff-42adc467cca6.png)

- 将节点插入到中间部分
127.0.0.1:6379> linsert lst after bb2 123
(integer) 10
`注：上面是将 “123” 添加到 “bb2”之后，因此列表中所存储的元素应该是：
aa1 aa2 aa3 bb1 bb2 123 bb3 cc1 cc2 cc3`

因为存储了值 bb2 的 quicklistNode 是满的了, 这个节点会被拆开
（我认为下图存些问题）
![image](https://user-images.githubusercontent.com/18511674/73904928-92b9b000-48d8-11ea-8e66-e8b9389f48dc.png)

下面是我认为内部的存储结构示意图： （绿色的箭头代表的是指针），请指教
![image](https://user-images.githubusercontent.com/18511674/73904918-89c8de80-48d8-11ea-88ef-a2d44bdc7fbe.png)

**Comment by zpoint** [comment]
感谢指正, 已更改, 现在顺序是一致的了

	127.0.0.1:6379> lrange lst 0 -1
	1) "cc3"
	2) "cc2"
	3) "cc1"
	4) "bb3"
	5) "bb2"
	6) "bb1"
	7) "aa3"
	8) "aa2"
	9) "aa1"
    127.0.0.1:6379> linsert lst after bb2 123
	(integer) 10
	127.0.0.1:6379> lrange lst 0 -1
	 1) "cc3"
	 2) "cc2"
	 3) "cc1"
	 4) "bb3"
	 5) "bb2"
	 6) "123"
	 7) "bb1"
	 8) "aa3"
	 9) "aa2"
	10) "aa1"
