### ISSUE TITLE
sdiff算法复杂度问题

### ISSUE THREAD

**Issue by scyslz** [zpoint/Redis-Internals#19]
算法一的复杂度明显不是O(N*M)吧

**Comment by zpoint** [comment]
最差情况下是吧, 对于第 0 个集合的N个元素, 在剩下的M个集合中都进行一遍查询

[原始代码](https://github.com/redis/redis/blob/5e908a290ccbe9c4a7bea9356faf3b837df62793/src/t_set.c), 在注释部分有作者的分析
